site_name: CosìMiPiace
site_url: https://readthedocs.org/projects/readthedocscomepiaceame/
site_description: Un altro bel tool per scrivere documentazione in Markdown

repo_url: https://github.com/aborruso/readthedocscomepiaceame
repo_name: readthedocscomepiaceame
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo.png
  palette:
    scheme: preference
  language: it

nav:
  - Home: README.md
  - twarc2: twarc2.md
  - Plugins: plugins.md
  - Twitter Developer Access: twitter-developer-access.md
  - Windows 10: windows10.md
  - Library API:
    - api/client.md
    - api/client2.md
    - api/expansions.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
